services:
  qr-scanner-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr_scanner_service
    restart: always
    privileged: true
    env_file:
      - .env
    volumes:
      # Mount /dev to support USB hotplugging even if scanner is not connected yet
      - /dev:/dev
      # Mount certificates directory as read-only (:ro)
      - ${HOST_CERTS_DIR:-./certs}:${AWS_CERT_DIR:-/app/certs}:ro

